-- =============================================================================
-- Check-in QR isoloir : toutes les requêtes Neon, dans l'ordre
-- =============================================================================
--
-- À exécuter dans la console Neon → SQL Editor, étape par étape (pas tout d'un coup).
-- Vérifier en haut de l'éditeur quelle BRANCHE est sélectionnée avant chaque exécution.
--
--   Étape 1  : créer les tables            → branche de test ET prod (une seule fois par base)
--   Étape 2  : vérifier les tables         → branche de test ET prod
--   Étape 3  : données de test             → branche de test UNIQUEMENT
--   Étape 4  : isoloirs réels              → prod (le jour de l'installation)
--   Étape 5  : requêtes utiles             → consultation / remise à zéro
--   Annexe   : supprimer les tables        → branche de test uniquement
--
-- Le back vérifie le schéma au démarrage (ddl-auto=validate) : l'étape 1 doit être faite
-- AVANT de démarrer une version du back qui contient le check-in, sinon il refuse de démarrer.
--
-- Rappel .env : chaque branche Neon a sa propre adresse (ep-xxxx…). Pour tester sur la branche,
-- DB_URL dans back/.env doit pointer vers l'adresse de la branche, pas vers celle de la prod.


-- =============================================================================
-- ÉTAPE 1 : créer les tables du check-in (branche de test ET prod, une seule fois)
-- =============================================================================
-- Même contenu que migration-postgres.sql. N'ajoute que 3 tables, ne modifie aucune table existante.
-- Si Neon répond « relation "isoloir" already exists » : c'est déjà fait, passer à l'étape 2.

BEGIN;

CREATE TABLE isoloir (
	id_isoloir INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	libelle VARCHAR(50) NOT NULL,
	actif BOOLEAN NOT NULL DEFAULT TRUE,
	-- Clé HMAC (hex, 32 octets) qui signe les QR de cet isoloir. Ne quitte jamais le serveur.
	cle_hmac VARCHAR(64) NOT NULL,
	-- SHA-256 (hex) de la clé que le poste isoloir envoie pour récupérer son QR
	cle_tablette_hash VARCHAR(64) NOT NULL
);

-- Un émargement par inscription : c'est cette contrainte qui empêche deux check-in valides
CREATE TABLE emargement_isoloir (
	id_emargement INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_inscription INTEGER NOT NULL REFERENCES inscription (id_inscription),
	id_isoloir INTEGER NOT NULL REFERENCES isoloir (id_isoloir),
	emarge_le TIMESTAMP NOT NULL,
	CONSTRAINT uq_emargement_inscription UNIQUE (id_inscription)
);

-- Audit / debug uniquement
CREATE TABLE journal_checkin (
	id_journal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_utilisateur INTEGER REFERENCES utilisateur (id_utilisateur),
	id_isoloir INTEGER REFERENCES isoloir (id_isoloir),
	scanne_le TIMESTAMP NOT NULL,
	resultat VARCHAR(20) NOT NULL,
	CONSTRAINT chk_resultat_checkin CHECK (resultat IN ('success', 'already_voted', 'expired_token', 'invalid_token', 'not_registered'))
);

CREATE INDEX idx_journal_checkin_utilisateur ON journal_checkin (id_utilisateur);

COMMIT;


-- =============================================================================
-- ÉTAPE 2 : vérifier que les tables existent (branche de test ET prod)
-- =============================================================================
-- Doit renvoyer 3 lignes : emargement_isoloir, isoloir, journal_checkin

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('isoloir', 'emargement_isoloir', 'journal_checkin')
ORDER BY table_name;


-- =============================================================================
-- ÉTAPE 3 : données de test (BRANCHE DE TEST UNIQUEMENT, jamais en prod)
-- =============================================================================

-- 3a. Un isoloir de test, avec la clé poste "cle-test-isoloir".
--     Noter l'id_isoloir renvoyé.
INSERT INTO isoloir (libelle, cle_hmac, cle_tablette_hash)
VALUES ('Isoloir test', encode(sha256(gen_random_uuid()::text::bytea), 'hex'),
        encode(sha256('cle-test-isoloir'::bytea), 'hex'))
RETURNING id_isoloir;

-- 3b. Trouver la période ouverte : noter l'id_periode de la ligne où statut = true.
--     S'il n'y en a aucune, ne pas en ouvrir une au hasard (c'est l'admin qui gère les périodes).
SELECT id_periode, statut, ouvert_le, clos_le FROM periode_vote ORDER BY id_periode;

-- 3c. Démarrer le back avec le profil demo (uniquement sur la branche de test !) :
--       cd back && ./mvnw spring-boot:run -Dspring-boot.run.profiles=demo
--     Il crée le compte électeur test@mydigitalschool.fr / root
--     (et le compte admin root@demo.fr / root : c'est pour ça que le profil demo ne doit JAMAIS tourner sur la prod).

-- 3d. Inscrire ce compte à la période ouverte (remplacer <id_periode> par le numéro noté en 3b).
INSERT INTO inscription (id_utilisateur, id_periode)
SELECT id_utilisateur, <id_periode> FROM utilisateur WHERE email = 'test@mydigitalschool.fr'
ON CONFLICT DO NOTHING;

-- 3e. Tester :
--       cd front && npm run dev:https
--       PC        : https://localhost:5173/isoloir/<id_isoloir>?cle=cle-test-isoloir
--       Téléphone : https://<ip-du-pc>:5173/ → test@mydigitalschool.fr / root → « Isoloir » → scanner


-- =============================================================================
-- ÉTAPE 4 : isoloirs réels (PROD, le jour de l'installation)
-- =============================================================================
-- Pour CHAQUE poste isoloir :
--   1. Générer une clé poste aléatoire dans un terminal (ne jamais réutiliser "cle-test-isoloir") :
--        openssl rand -hex 24
--   2. Remplacer <clé poste> ci-dessous par cette clé, et <libellé> par le nom du poste.
--      La base ne garde que l'empreinte SHA-256 de la clé, jamais la clé elle-même.
--   3. Ouvrir sur le poste : https://<adresse-de-l-appli>/isoloir/<id_isoloir>?cle=<clé poste>
--      puis effacer l'historique du navigateur (voir la checklist du README).
--   Ne pas enregistrer la clé poste dans ce fichier ni dans le dépôt.

INSERT INTO isoloir (libelle, cle_hmac, cle_tablette_hash)
VALUES ('<libellé>', encode(sha256(gen_random_uuid()::text::bytea), 'hex'),
        encode(sha256('<clé poste>'::bytea), 'hex'))
RETURNING id_isoloir;

-- Poste perdu ou manipulé : le désactiver (ses QR sont refusés immédiatement), puis en créer un nouveau.
UPDATE isoloir SET actif = FALSE WHERE id_isoloir = <id_isoloir>;


-- =============================================================================
-- ÉTAPE 5 : requêtes utiles
-- =============================================================================

-- Liste des isoloirs (sans afficher les clés)
SELECT id_isoloir, libelle, actif FROM isoloir ORDER BY id_isoloir;

-- Nombre d'émargements par isoloir
SELECT i.libelle, count(e.id_emargement) AS emargements
FROM isoloir i LEFT JOIN emargement_isoloir e ON e.id_isoloir = i.id_isoloir
GROUP BY i.libelle ORDER BY i.libelle;

-- Derniers scans (réussis et refusés), du plus récent au plus ancien
SELECT j.scanne_le, u.email, j.id_isoloir, j.resultat
FROM journal_checkin j LEFT JOIN utilisateur u ON u.id_utilisateur = j.id_utilisateur
ORDER BY j.scanne_le DESC
LIMIT 50;

-- Refaire un test avec le même compte (BRANCHE DE TEST UNIQUEMENT) :
-- supprime son émargement pour qu'il puisse scanner à nouveau
DELETE FROM emargement_isoloir WHERE id_inscription IN (
	SELECT i.id_inscription FROM inscription i JOIN utilisateur u USING (id_utilisateur)
	WHERE u.email = 'test@mydigitalschool.fr');


-- =============================================================================
-- ANNEXE : tout supprimer (BRANCHE DE TEST UNIQUEMENT)
-- =============================================================================
-- Retire les 3 tables du check-in. Attention : une version du back qui contient le check-in
-- ne démarrera plus sur cette base tant que l'étape 1 n'est pas refaite.

-- BEGIN;
-- DROP TABLE journal_checkin;
-- DROP TABLE emargement_isoloir;
-- DROP TABLE isoloir;
-- COMMIT;
