-- Check-in QR isoloir : tables à ajouter dans la base Neon de l'appli.
-- S'appuie sur les tables existantes utilisateur, inscription (et bulletin pour le statut).
-- À lancer une seule fois, dans une transaction.

BEGIN;

CREATE TABLE isoloir (
	id_isoloir INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	libelle VARCHAR(50) NOT NULL,
	actif BOOLEAN NOT NULL DEFAULT TRUE,
	-- Clé HMAC (hex, 32 octets) qui signe les QR de cet isoloir. Ne quitte jamais le serveur.
	cle_hmac VARCHAR(64) NOT NULL,
	-- SHA-256 (hex) de la clé que la tablette envoie pour récupérer son QR
	cle_tablette_hash VARCHAR(64) NOT NULL
);

-- Un émargement par inscription : c'est cette contrainte qui empêche deux check-in valides
CREATE TABLE emargement_isoloir (
	id_emargement INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_inscription INTEGER NOT NULL REFERENCES inscription (id_inscription),
	id_isoloir INTEGER NOT NULL REFERENCES isoloir (id_isoloir),
	emarge_le TIMESTAMP NOT NULL,
	CONSTRAINT uq_emargement_inscription UNIQUE (id_inscription)
);

-- Audit / debug uniquement
CREATE TABLE journal_checkin (
	id_journal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_utilisateur INTEGER REFERENCES utilisateur (id_utilisateur),
	id_isoloir INTEGER REFERENCES isoloir (id_isoloir),
	scanne_le TIMESTAMP NOT NULL,
	resultat VARCHAR(20) NOT NULL,
	CONSTRAINT chk_resultat_checkin CHECK (resultat IN ('success', 'already_voted', 'expired_token', 'invalid_token', 'not_registered'))
);

CREATE INDEX idx_journal_checkin_utilisateur ON journal_checkin (id_utilisateur);

COMMIT;

-- Ajout d'un isoloir (à faire pour chaque tablette) :
--   1. choisir une clé tablette longue et aléatoire, ex. : openssl rand -hex 24
--   2. INSERT INTO isoloir (libelle, cle_hmac, cle_tablette_hash)
--      VALUES ('Isoloir 1', encode(sha256(gen_random_uuid()::text::bytea), 'hex'),
--              encode(sha256('<clé tablette>'::bytea), 'hex'));
--   3. ouvrir sur la tablette : https://<front>/isoloir/<id_isoloir>?cle=<clé tablette>
