spring.application.name=election-api
spring.datasource.url=jdbc:postgresql://localhost:5432/election
spring.datasource.username=election
spring.datasource.password=election
spring.jpa.hibernate.ddl-auto=update

# Front autorisé à appeler l API (Next/Nuxt : 3000, Vite : 5173)
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173
spring.jpa.open-in-view=false
