-- Copie minimale des tables existantes de l'appli (seulement les colonnes utiles au check-in)

CREATE TABLE utilisateur (
	id_utilisateur INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	matricule VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE periode_vote (
	id_periode INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	statut BOOLEAN NOT NULL DEFAULT FALSE,
	ouvert_le DATE,
	clos_le DATE
);

CREATE TABLE inscription (
	id_inscription INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_utilisateur INTEGER NOT NULL REFERENCES utilisateur (id_utilisateur),
	id_periode INTEGER NOT NULL REFERENCES periode_vote (id_periode),
	inscrit_le DATE NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT uq_inscription UNIQUE (id_utilisateur, id_periode)
);

CREATE TABLE bulletin (
	id_bulletin INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_inscription INTEGER NOT NULL UNIQUE REFERENCES inscription (id_inscription),
	depose_le DATE NOT NULL DEFAULT CURRENT_DATE
);

-- Nouvelles tables du check-in (identiques à ../../sql/migration-postgres.sql)

CREATE TABLE isoloir (
	id_isoloir INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	libelle VARCHAR(50) NOT NULL,
	actif BOOLEAN NOT NULL DEFAULT TRUE,
	cle_hmac VARCHAR(64) NOT NULL,
	cle_tablette_hash VARCHAR(64) NOT NULL
);

CREATE TABLE emargement_isoloir (
	id_emargement INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_inscription INTEGER NOT NULL REFERENCES inscription (id_inscription),
	id_isoloir INTEGER NOT NULL REFERENCES isoloir (id_isoloir),
	emarge_le TIMESTAMP NOT NULL,
	CONSTRAINT uq_emargement_inscription UNIQUE (id_inscription)
);

CREATE TABLE journal_checkin (
	id_journal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_utilisateur INTEGER REFERENCES utilisateur (id_utilisateur),
	id_isoloir INTEGER REFERENCES isoloir (id_isoloir),
	scanne_le TIMESTAMP NOT NULL,
	resultat VARCHAR(20) NOT NULL,
	CONSTRAINT chk_resultat_checkin CHECK (resultat IN ('success', 'already_voted', 'expired_token', 'invalid_token', 'not_registered'))
);
